# Generated by Django 5.2.5 on 2025-09-08 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={},
        ),
        migrations.RemoveField(
            model_name='claim',
            name='adjuster_name',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_amount',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_number',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_type',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claimant_address',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claimant_email',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claimant_name',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claimant_phone',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='id',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='claim',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='discharge_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='insurer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('denied', 'Denied')], default='pending', max_length=255),
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpt_code', models.CharField(default='', max_length=255)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErisaApp.claim')),
            ],
        ),
    ]
