# Generated by Django 5.2.5 on 2025-09-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaApp', '0002_alter_claim_options_remove_claim_adjuster_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='patient_name',
            field=models.CharField(default='hgello', max_length=255),
        ),
    ]
