# Generated by Django 5.2.5 on 2025-09-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaApp', '0003_alter_claim_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='patient_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
