# Generated by Django 5.2.5 on 2025-09-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaApp', '0004_alter_claim_patient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimDetail',
        ),
    ]
