# Generated by Django 5.2.5 on 2025-09-13 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaApp', '0005_delete_claimdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-claim_id']},
        ),
        migrations.AddField(
            model_name='claim',
            name='cpt_codes',
            field=models.TextField(blank=True, help_text='Comma-separated CPT codes', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpt_code', models.CharField(default='', max_length=255)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErisaApp.claim')),
            ],
        ),
    ]
