# Generated by Django 5.2.5 on 2025-09-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErisaApp', '0007_remove_claim_cpt_codes_remove_claim_denial_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('denied', 'Denied'), ('under_review', 'Under Review')], default='pending', max_length=255),
        ),
    ]
