# Generated by Django 5.2.5 on 2025-09-08 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(help_text='Unique claim identifier', max_length=50, unique=True)),
                ('claim_number', models.CharField(blank=True, help_text='External claim number', max_length=100)),
                ('claimant_name', models.CharField(help_text='Name of the claimant', max_length=200)),
                ('claimant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('claimant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('claimant_address', models.TextField(blank=True, null=True)),
                ('claim_type', models.CharField(help_text='Type of claim (e.g., Medical, Property, Auto)', max_length=100)),
                ('claim_description', models.TextField(help_text='Description of the claim')),
                ('incident_date', models.DateField(help_text='Date when the incident occurred')),
                ('claim_date', models.DateField(help_text='Date when the claim was filed')),
                ('claim_amount', models.DecimalField(decimal_places=2, help_text='Claimed amount', max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approved amount', max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('paid', 'Paid'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adjuster_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
